name: Distribute

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Distribute for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Call dist (test & build)
      run: bash ./dist.sh
